// <auto-generated />
using Accumulator.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Accumulator.Migrations
{
    [DbContext(typeof(AccumulatorDbContext))]
    partial class AccumulatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Accumulator.Domain.ItemDefinitions.ItemDefinition", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<int>("GradeType")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsStackable")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<byte>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(4);

                    b.HasKey("Code");

                    b.ToTable("ItemDefinitions", (string)null);
                });

            modelBuilder.Entity("Accumulator.Domain.ItemDefinitions.ItemDefinition", b =>
                {
                    b.OwnsOne("Accumulator.Domain.ItemDefinitions.ItemDefinition.Size#Accumulator.Domain.ItemDefinitions.ItemSize", "Size", b1 =>
                        {
                            b1.Property<string>("ItemDefinitionCode")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Height")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Height")
                                .HasColumnOrder(6);

                            b1.Property<int>("Width")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Width")
                                .HasColumnOrder(7);

                            b1.HasKey("ItemDefinitionCode");

                            b1.ToTable("ItemDefinitions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ItemDefinitionCode");
                        });

                    b.OwnsMany("Accumulator.Domain.ItemDefinitions.ItemDefinition.Grades#Accumulator.Domain.ItemDefinitions.ItemDefinitionGrade", "Grades", b1 =>
                        {
                            b1.Property<string>("ParentCode")
                                .HasColumnType("TEXT")
                                .HasColumnOrder(0);

                            b1.Property<string>("Code")
                                .HasColumnType("TEXT")
                                .HasColumnOrder(1);

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER")
                                .HasColumnOrder(2);

                            b1.HasKey("ParentCode", "Code");

                            b1.HasIndex("Code");

                            b1.ToTable("ItemDefinitionGrades", (string)null);

                            b1.HasOne("Accumulator.Domain.ItemDefinitions.ItemDefinition", null)
                                .WithMany()
                                .HasForeignKey("Code")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("ParentCode");
                        });

                    b.Navigation("Grades");

                    b.Navigation("Size")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
