// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage(
    "Design",
    "CA1062:Validate arguments of public methods",
    Scope = "namespaceanddescendants",
    Target = "~N:Accumulator.Migrations",
    Justification = "Migrations are executed by Entity Framework Core and the builder parameter will not be null.")]

[assembly: SuppressMessage(
    "Minor Code Smell",
    "S1192:String literals should not be duplicated",
    Scope = "namespaceanddescendants",
    Target = "~N:Accumulator.Migrations",
    Justification = "Constants are generated by Entity Framework Core and would create unnecessary extra work to centralize.")]

[assembly: SuppressMessage(
    "StyleCop.CSharp.DocumentationRules",
    "SA1649:File name should match first type name",
    Scope = "namespaceanddescendants",
    Target = "~N:Accumulator.Migrations",
    Justification = "Migrations have a data prepended to the file but should not use it in the class name for readability.")]
